#!/usr/bin/env python
import sys


def coverage():
    """
    Create console and HTML coverage reports for the full test suite.
    """
    import nose
    from coverage import coverage

    omit = [
        '*testcase*',
        '*test_*']

    cov = coverage(
        branch=True, config_file=False, source=['personalsite'],
        omit=omit)

    cov.start()

    nose.run(argv=['nose', '-w', 'personalsite'] + sys.argv[1:])

    cov.stop()

    cov.report()
    cov.html_report(directory='../cover')

if __name__ == '__main__':
    coverage()
