#!/usr/bin/env python
import os
import json
import sys
import subprocess

data = json.loads(sys.stdin.read())
files = data['files']


def check_coverage():
    cwd = os.getcwd()

    wd = os.path.join(os.path.dirname(__file__), '..', '..')
    os.chdir(wd)
    try:
        subprocess.check_call([
            'vagrant', 'ssh', '-c',
            'cd /vagrant; ./scripts/coverage --cover-min-percentage 100'
        ], stdout=open('/dev/null', 'w'))
    except subprocess.CalledProcessError:
        return [('s', 'Test coverage is not at 100%')]

    os.chdir(cwd)

out = None

for f in files:
    if f['name'].endswith('.py'):
        out = check_coverage()
        break

sys.stdout.write(json.dumps(out, indent=4))

sys.exit(0)
